% I1 = rand(200, 200) ;
% I2 = imrotate( I1, 1, 'bicubic', 'crop') ;
% [Uhs, Vhs] = hornschunck(I1, I2, 0.5, 10);
% [Ulk, Vlk] = lucaskanade(I1, I2, 3);
% figure(1); clf;
% hold on;
% subplot(2, 3, 1); imshow(I1); title('Slika1');
% subplot(2, 3, 4); imshow(I2); title('Slika2');
% subplot(2, 3, 2); showflow(Uhs, Vhs, 'color'); title('HornSchunck');
% subplot(2, 3, 3); showflow(Ulk, Vlk, 'color'); title('LucasKanade');
% subplot(2, 3, 5); showflow(Uhs, Vhs, 'field'); title('HornSchunck');
% subplot(2, 3, 6); showflow(Ulk, Vlk, 'field'); title('LucasKanade');
% hold off ;
I1 = mat2gray(imread('lab2\014.jpg'));
I2= mat2gray(imread('lab2\015.jpg'));
%H = harriscorners(I1, 10);
[Uhs, Vhs] = hornschunck(I1, I2, 0.5, 100);
[Ulk, Vlk] = hornschunck(I1, I2, 0.5, 2000);
figure(1); clf;
hold on;
subplot(2, 3, 1); imshow(I1); title('Slika1');
subplot(2, 3, 4); imshow(I2); title('Slika2');
subplot(2, 3, 2); showflow(Uhs, Vhs, 'color'); title('HornSchunck 100');
subplot(2, 3, 3); showflow(Ulk, Vlk, 'color'); title('HornSchunck 2000');
subplot(2, 3, 5); showflow(Uhs, Vhs, 'field'); title('HornSchunck 100');
subplot(2, 3, 6); showflow(Ulk, Vlk, 'field'); title('HornSchunck 2000');
hold off ;